server:
  port: 8082
  address: 0.0.0.0
spring:
  application:
    name: inventario-service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8888}
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 2000
        max-attempts: 10
        multiplier: 1.5
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/8680c901-cdee-41fb-b489-95b35c8ffaf0/discovery/v2.0/keys
          audiences: c64efc77-580d-403d-bd8e-f89813aa0265

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.security.oauth2: DEBUG